version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
      - persist_to_workspace:
          root: .
          paths: dist
  deploy:
    machine: true
    steps:
      - attach_workspace:
          at: ~/project
      - run: echo ${HOST_FINGERPRINT} >> ~/.ssh/known_hosts
      - run: sudo apt install rsync
      - run: rsync -rhv --delete dist/ sfcandle@zarniwoop.dreamhost.com:/home/sfcandle/grid.sfcandle.co/
# comment

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master