version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    # working_directory: ~/gridsome-forestry-starter
    # working_directory: ~/project
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            # - persist_to_workspace:
            #     root: dist
            #     paths:
            #       - dist
      - persist_to_workspace:
          root: .
          paths: dist
  deploy:
    executor:
      name: node/default
    # working_directory: ~/gridsome-forestry-starter
    steps:
      - attach_workspace:
          at: ~/project
  #     - run: pwd
      # - attach_workspace:
          # at: dist
      - run: ls
      - run: echo ${HOST_FINGERPRINT} >> ~/.ssh/known_hosts
      - run: sudo apt install rsync
      - run: rsync -rhv --delete dist/ sfcandle@zarniwoop.dreamhost.com:/home/sfcandle/grid.sfcandle.co/
  #     - run: ls -la
  #     - run: scp -r dist/* sfcandle@zarniwoop.dreamhost.com:/home/sfcandle/grid.sfcandle.co


workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
      #     filters:
      #       branches:
      #         only: master