version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm build
  deploy:
    machine:
      enabled: true
    steps:
      - run: scp -r gridsome-forestry-starter/dist/* sfcandle@zarniwoop.dreamhost.com:/home/sfcandle/grid.sfcandle.co


workflows:
    build-and-deploy:
      jobs:
        - build
        - deploy:
          requires:
            - build
          filters:
            branches:
              only: master